### ISSUE TITLE
Comments not displayed on deployed version

### ISSUE THREAD

**Issue by Domene99** [Domene99/STEP#7]
When adding a second sort, I receive an error code 500 from /comment servlet. Log says "no matching index found" line of code: https://github.com/Domene99/STEP/blob/7894a20fdb32ed01876bf8a2dbb892be73556c41/portfolio/src/main/java/com/google/sps/servlets/DataServlet.java#L47

**Comment by Domene99** [comment]
Should work according to https://github.com/greghaskins/googleappengine/blob/e78ea5c1ef55564b776ff155630202afb2d4ecfa/java/src/main/com/google/appengine/api/datastore/Query.java#L262

**Comment by Domene99** [comment]
Temporary fix seems to be removing the second sort

**Comment by Domene99** [comment]
Even when explicitely writing it like seen on the testing method it fails to work on deployed version https://github.com/GoogleCloudPlatform/appengine-tck/blob/a5c504bc0e84e27aa5fcba89eb57aa2a8feccc6f/tests/appengine-tck-datastore/src/test/java/com/google/appengine/tck/datastore/RequiredIndexesTest.java#L258

**Comment by ssmall** [comment]
So it seems like what is happening here is you are hitting an issue with [Indexes in Cloud Datastore][]. According to that page, it seems that if you want to be able to query with a secondary sort, you will need a composite index on both columns.

[Indexes in Cloud Datastore]: https://cloud.google.com/datastore/docs/concepts/indexes

**Comment by Domene99** [comment]
For me these two columns should not be indexed together by design. Removing double sorting feature and closing issue. Still find it weird that it does work on the local version.
